# base image
FROM node:10.16-alpine

# set working directory. if not exist, it will be created.
# WORKDIR can be used multiple times. each time, it will be relative to the previous WORKDIR path
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent

# start app
CMD ["npm", "start"]
